Feat/#12 이벤트 상세페이지 퍼블리싱
Kpop-Goods/Kg-FE pull request #13
Opened 2024-02-22 07:17 UTC by quswjdgma83

## 1. 연관된 이슈 번호

- #11 

<br>

## 2. 작업 내용

- 이벤트상세세페이지 퍼블리싱
- chore은 svg 및 png 파일입니다. 

<br>

## 3. 스크린샷 (선택사항)
![image](https://github.com/Kpop-Goods/Kg-FE/assets/111037279/93f586d0-8d11-4a0f-9a30-0e22e4c20092)

<br>

## 4. 추가사항 및 리뷰 요구사항 (선택사항)

2024-02-23 07:56 UTC, ijaesin requested changes

2024-02-23 07:56 UTC, ijaesin commented on app/events/[id]/page.tsx
> +  const formatEventDates = (startDate: string, endDate: string) => {
함수 같은 경우에, 해당 페이지가 이외에도 재사용될 여지가 있을경우 @/utils 폴더에서 정의하는게 더 좋아보입니다 !

2024-02-23 07:56 UTC, ijaesin commented on app/events/page.tsx
> +              <EventCard key={event.eventId} {...event} />
Type error: Type '{ eventId: number; eventCategoryCd: number; eventName: string; placeName: string; address: string; streetAddress: string; detailAddress: string; content: string; notes: string; eventUrl: null; ... 14 more ...; key: number; }' is missing the following properties from type 'EventCardProps': placeId, placeCategoryCode, placeAddress, placeImg, and 2 more.

vercel에서 자동검사 결과, 타입 에러가 있다고 하네요 ! EventCard.tsx 에서 타입을 추가해야될 것 같습니다.

2024-02-25 07:17 UTC, quswjdgma83 commented on app/events/[id]/page.tsx
> +  const formatEventDates = (startDate: string, endDate: string) => {
넵 확인했습니다!

2024-02-25 13:13 UTC, ijaesin approved these changes
LGTM

2024-02-26 00:04 UTC, merged